// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cuda.proto

#include "cuda.pb.h"
#include "cuda.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace cuda_compute {

static const char* CudaComputeService_method_names[] = {
  "/cuda_compute.CudaComputeService/CudaCompute",
};

std::unique_ptr< CudaComputeService::Stub> CudaComputeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CudaComputeService::Stub> stub(new CudaComputeService::Stub(channel, options));
  return stub;
}

CudaComputeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CudaCompute_(CudaComputeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CudaComputeService::Stub::CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::cuda_compute::CudaComputeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CudaCompute_, context, request, response);
}

void CudaComputeService::Stub::async::CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CudaCompute_, context, request, response, std::move(f));
}

void CudaComputeService::Stub::async::CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CudaCompute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>* CudaComputeService::Stub::PrepareAsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cuda_compute::CudaComputeResponse, ::cuda_compute::CudaComputeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CudaCompute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>* CudaComputeService::Stub::AsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCudaComputeRaw(context, request, cq);
  result->StartCall();
  return result;
}

CudaComputeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CudaComputeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CudaComputeService::Service, ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CudaComputeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cuda_compute::CudaComputeRequest* req,
             ::cuda_compute::CudaComputeResponse* resp) {
               return service->CudaCompute(ctx, req, resp);
             }, this)));
}

CudaComputeService::Service::~Service() {
}

::grpc::Status CudaComputeService::Service::CudaCompute(::grpc::ServerContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cuda_compute

