// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cuda.proto
#ifndef GRPC_cuda_2eproto__INCLUDED
#define GRPC_cuda_2eproto__INCLUDED

#include "cuda.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace cuda_compute {

class CudaComputeService final {
 public:
  static constexpr char const* service_full_name() {
    return "cuda_compute.CudaComputeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::cuda_compute::CudaComputeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>> AsyncCudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>>(AsyncCudaComputeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>> PrepareAsyncCudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>>(PrepareAsyncCudaComputeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>* AsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cuda_compute::CudaComputeResponse>* PrepareAsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::cuda_compute::CudaComputeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>> AsyncCudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>>(AsyncCudaComputeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>> PrepareAsyncCudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>>(PrepareAsyncCudaComputeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, std::function<void(::grpc::Status)>) override;
      void CudaCompute(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>* AsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cuda_compute::CudaComputeResponse>* PrepareAsyncCudaComputeRaw(::grpc::ClientContext* context, const ::cuda_compute::CudaComputeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CudaCompute_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CudaCompute(::grpc::ServerContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CudaCompute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCudaCompute(::grpc::ServerContext* context, ::cuda_compute::CudaComputeRequest* request, ::grpc::ServerAsyncResponseWriter< ::cuda_compute::CudaComputeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CudaCompute<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CudaCompute() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cuda_compute::CudaComputeRequest* request, ::cuda_compute::CudaComputeResponse* response) { return this->CudaCompute(context, request, response); }));}
    void SetMessageAllocatorFor_CudaCompute(
        ::grpc::MessageAllocator< ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CudaCompute(
      ::grpc::CallbackServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CudaCompute<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CudaCompute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CudaCompute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCudaCompute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CudaCompute() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CudaCompute(context, request, response); }));
    }
    ~WithRawCallbackMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CudaCompute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CudaCompute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CudaCompute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cuda_compute::CudaComputeRequest, ::cuda_compute::CudaComputeResponse>* streamer) {
                       return this->StreamedCudaCompute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CudaCompute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CudaCompute(::grpc::ServerContext* /*context*/, const ::cuda_compute::CudaComputeRequest* /*request*/, ::cuda_compute::CudaComputeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCudaCompute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cuda_compute::CudaComputeRequest,::cuda_compute::CudaComputeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CudaCompute<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CudaCompute<Service > StreamedService;
};

}  // namespace cuda_compute


#endif  // GRPC_cuda_2eproto__INCLUDED
